name: Build Custom Web Template
on: workflow_dispatch

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: 4.6.1-stable

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.45

      - name: Setup Python & SCons
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install SCons
        run: pip install scons

      - name: Compilation
        run: |
          scons platform=web target=template_release precision=single \
          disable_3d=no \
          disable_advanced_gui=yes \
          module_physics_2d_enabled=no \
          module_physics_3d_enabled=yes \
          module_navigation_enabled=no \
          module_mobile_vr_enabled=no \
          module_openxr_enabled=no \
          module_camera_enabled=no \
          module_msdfgen_enabled=no \
          module_text_server_adv_enabled=no \
          module_text_server_fb_enabled=yes \
          module_upnp_enabled=no \
          module_enet_enabled=no \
          module_dds_enabled=no \
          module_tga_enabled=no \
          module_webxr_enabled=no \
          optimize=size \
          -j$(nproc)

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: custom-web-template
          path: bin/godot.web.template_release.wasm32.zip
